import { UserModel, type UserRole } from "@/api/auth/user.model";
import { DoctorModel } from "@/api/doctor/doctor.model";
import { PatientModel } from "@/api/patient/patient.model";
import { connectToDatabase, disconnectFromDatabase } from "@/common/db/db";
import { env } from "@/common/utils/envConfig";
import { hash } from "bcryptjs";

const adminCredentials = {
  name: "Admin User",
  email: "admin@doctortracker.local",
  password: "Admin@12345",
  role: "ADMIN" satisfies UserRole,
};

const doctors = [
  {
    name: "Dr. Ayesha Rahman",
    specialization: "Cardiology",
    hospital: "Care Guide Medical Center",
    phone: "+8801711000001",
    email: "ayesha.rahman@example.com",
  },
  {
    name: "Dr. Tanvir Hasan",
    specialization: "Neurology",
    hospital: "City Health Hospital",
    phone: "+8801711000002",
    email: "tanvir.hasan@example.com",
  },
  {
    name: "Dr. Nusrat Karim",
    specialization: "Pediatrics",
    hospital: "Metro Children Hospital",
    phone: "+8801711000003",
    email: "nusrat.karim@example.com",
  },
  {
    name: "Dr. Omar Faruque",
    specialization: "Orthopedics",
    hospital: "Care Guide Medical Center",
    phone: "+8801711000004",
    email: "omar.faruque@example.com",
  },
  {
    name: "Dr. Sadia Chowdhury",
    specialization: "Dermatology",
    hospital: "Green Life Hospital",
    phone: "+8801711000005",
    email: "sadia.chowdhury@example.com",
  },
  {
    name: "Dr. Imran Kabir",
    specialization: "Endocrinology",
    hospital: "Central Diabetic Care",
    phone: "+8801711000006",
    email: "imran.kabir@example.com",
  },
  {
    name: "Dr. Rifat Ahmed",
    specialization: "Pulmonology",
    hospital: "National Chest Institute",
    phone: "+8801711000007",
    email: "rifat.ahmed@example.com",
  },
  {
    name: "Dr. Samia Sultana",
    specialization: "Gynecology",
    hospital: "Mother Care Hospital",
    phone: "+8801711000008",
    email: "samia.sultana@example.com",
  },
  {
    name: "Dr. Hasan Mahmud",
    specialization: "Nephrology",
    hospital: "City Health Hospital",
    phone: "+8801711000009",
    email: "hasan.mahmud@example.com",
  },
  {
    name: "Dr. Priyanka Das",
    specialization: "Oncology",
    hospital: "Delta Cancer Center",
    phone: "+8801711000010",
    email: "priyanka.das@example.com",
  },
  {
    name: "Dr. Mehedi Alam",
    specialization: "ENT",
    hospital: "Metro General Hospital",
    phone: "+8801711000011",
    email: "mehedi.alam@example.com",
  },
  {
    name: "Dr. Farhana Yasmin",
    specialization: "Psychiatry",
    hospital: "Mind Wellness Clinic",
    phone: "+8801711000012",
    email: "farhana.yasmin@example.com",
  },
];

const daysFromToday = (offset: number) => {
  const date = new Date();
  date.setUTCHours(12, 0, 0, 0);
  date.setUTCDate(date.getUTCDate() + offset);
  return date;
};

const patientSeeds = [
  {
    doctorEmail: "ayesha.rahman@example.com",
    name: "Mahmudul Islam",
    phone: "+8801811000001",
    email: "mahmudul@example.com",
    age: 46,
    gender: "male",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(-10),
    notes: "Routine cardiac follow-up.",
  },
  {
    doctorEmail: "ayesha.rahman@example.com",
    name: "Farhana Akter",
    phone: "+8801811000002",
    email: "farhana@example.com",
    age: 58,
    gender: "female",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(-7),
    notes: "Requires close monitoring.",
  },
  {
    doctorEmail: "ayesha.rahman@example.com",
    name: "Rashed Karim",
    phone: "+8801811000005",
    email: "rashed.karim@example.com",
    age: 63,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(2),
    notes: "Blood pressure review scheduled.",
  },
  {
    doctorEmail: "tanvir.hasan@example.com",
    name: "Sajid Hossain",
    phone: "+8801811000003",
    email: "sajid.hossain@example.com",
    age: 37,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(1),
    notes: "Migraine assessment.",
  },
  {
    doctorEmail: "tanvir.hasan@example.com",
    name: "Anika Rahman",
    phone: "+8801811000006",
    email: "anika.rahman@example.com",
    age: 29,
    gender: "female",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(-3),
    notes: "Neurology follow-up after medication change.",
  },
  {
    doctorEmail: "tanvir.hasan@example.com",
    name: "Jahid Hasan",
    phone: "+8801811000007",
    email: "jahid.hasan@example.com",
    age: 41,
    gender: "male",
    condition: "recovering",
    status: "discharged",
    visitDate: daysFromToday(-14),
    notes: "Post-stroke rehabilitation review.",
  },
  {
    doctorEmail: "tanvir.hasan@example.com",
    name: "Sadia Zaman",
    phone: "+8801811000037",
    email: "sadia.zaman@example.com",
    age: 35,
    gender: "female",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(1),
    notes: "Neurological observation visit.",
  },
  {
    doctorEmail: "nusrat.karim@example.com",
    name: "Nabila Khan",
    phone: "+8801811000004",
    email: "nabila.khan@example.com",
    age: 8,
    gender: "female",
    condition: "recovering",
    status: "follow-up",
    visitDate: daysFromToday(-2),
    notes: "Pediatric recovery check.",
  },
  {
    doctorEmail: "nusrat.karim@example.com",
    name: "Arif Chowdhury",
    phone: "+8801811000008",
    email: "arif.chowdhury@example.com",
    age: 12,
    gender: "male",
    condition: "stable",
    status: "scheduled",
    visitDate: daysFromToday(4),
    notes: "Routine pediatric consultation.",
  },
  {
    doctorEmail: "nusrat.karim@example.com",
    name: "Maliha Sultana",
    phone: "+8801811000009",
    email: "maliha.sultana@example.com",
    age: 6,
    gender: "female",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(0),
    notes: "High fever observation.",
  },
  {
    doctorEmail: "nusrat.karim@example.com",
    name: "Rafi Ahmed",
    phone: "+8801811000038",
    email: "rafi.ahmed@example.com",
    age: 10,
    gender: "male",
    condition: "recovering",
    status: "follow-up",
    visitDate: daysFromToday(-2),
    notes: "Pediatric recovery follow-up.",
  },
  {
    doctorEmail: "omar.faruque@example.com",
    name: "Tariq Aziz",
    phone: "+8801811000010",
    email: "tariq.aziz@example.com",
    age: 54,
    gender: "male",
    condition: "recovering",
    status: "follow-up",
    visitDate: daysFromToday(-5),
    notes: "Knee replacement recovery.",
  },
  {
    doctorEmail: "omar.faruque@example.com",
    name: "Salma Begum",
    phone: "+8801811000011",
    email: "salma.begum@example.com",
    age: 68,
    gender: "female",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(6),
    notes: "Hip pain evaluation.",
  },
  {
    doctorEmail: "omar.faruque@example.com",
    name: "Nayeem Ahmed",
    phone: "+8801811000012",
    email: "nayeem.ahmed@example.com",
    age: 33,
    gender: "male",
    condition: "stable",
    status: "discharged",
    visitDate: daysFromToday(-12),
    notes: "Sports injury recovery.",
  },
  {
    doctorEmail: "sadia.chowdhury@example.com",
    name: "Shirin Akter",
    phone: "+8801811000013",
    email: "shirin.akter@example.com",
    age: 31,
    gender: "female",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(-1),
    notes: "Dermatitis follow-up.",
  },
  {
    doctorEmail: "sadia.chowdhury@example.com",
    name: "Rubel Mia",
    phone: "+8801811000014",
    email: "rubel.mia@example.com",
    age: 27,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(8),
    notes: "Allergy testing scheduled.",
  },
  {
    doctorEmail: "sadia.chowdhury@example.com",
    name: "Moumita Roy",
    phone: "+8801811000015",
    email: "moumita.roy@example.com",
    age: 24,
    gender: "female",
    condition: "recovering",
    status: "discharged",
    visitDate: daysFromToday(-9),
    notes: "Skin infection improved.",
  },
  {
    doctorEmail: "imran.kabir@example.com",
    name: "Abdul Matin",
    phone: "+8801811000016",
    email: "abdul.matin@example.com",
    age: 59,
    gender: "male",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(-4),
    notes: "Uncontrolled diabetes monitoring.",
  },
  {
    doctorEmail: "imran.kabir@example.com",
    name: "Mina Parvin",
    phone: "+8801811000017",
    email: "mina.parvin@example.com",
    age: 45,
    gender: "female",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(3),
    notes: "Thyroid medication review.",
  },
  {
    doctorEmail: "imran.kabir@example.com",
    name: "Hasibul Haque",
    phone: "+8801811000018",
    email: "hasibul.haque@example.com",
    age: 39,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(10),
    notes: "Glucose trend review.",
  },
  {
    doctorEmail: "rifat.ahmed@example.com",
    name: "Sonia Islam",
    phone: "+8801811000019",
    email: "sonia.islam@example.com",
    age: 34,
    gender: "female",
    condition: "recovering",
    status: "follow-up",
    visitDate: daysFromToday(-6),
    notes: "Asthma control follow-up.",
  },
  {
    doctorEmail: "rifat.ahmed@example.com",
    name: "Akbar Ali",
    phone: "+8801811000020",
    email: "akbar.ali@example.com",
    age: 71,
    gender: "male",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(0),
    notes: "COPD exacerbation.",
  },
  {
    doctorEmail: "rifat.ahmed@example.com",
    name: "Nusrat Jahan",
    phone: "+8801811000021",
    email: "nusrat.jahan@example.com",
    age: 40,
    gender: "female",
    condition: "stable",
    status: "discharged",
    visitDate: daysFromToday(-15),
    notes: "Respiratory infection resolved.",
  },
  {
    doctorEmail: "samia.sultana@example.com",
    name: "Lamia Begum",
    phone: "+8801811000022",
    email: "lamia.begum@example.com",
    age: 28,
    gender: "female",
    condition: "stable",
    status: "scheduled",
    visitDate: daysFromToday(5),
    notes: "Prenatal checkup.",
  },
  {
    doctorEmail: "samia.sultana@example.com",
    name: "Tasnim Ara",
    phone: "+8801811000023",
    email: "tasnim.ara@example.com",
    age: 36,
    gender: "female",
    condition: "observation",
    status: "follow-up",
    visitDate: daysFromToday(-8),
    notes: "Postnatal follow-up.",
  },
  {
    doctorEmail: "samia.sultana@example.com",
    name: "Ishrat Jahan",
    phone: "+8801811000024",
    email: "ishrat.jahan@example.com",
    age: 32,
    gender: "female",
    condition: "recovering",
    status: "discharged",
    visitDate: daysFromToday(-13),
    notes: "Procedure recovery check.",
  },
  {
    doctorEmail: "hasan.mahmud@example.com",
    name: "Mostafa Kamal",
    phone: "+8801811000025",
    email: "mostafa.kamal@example.com",
    age: 66,
    gender: "male",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(-1),
    notes: "Kidney function monitoring.",
  },
  {
    doctorEmail: "hasan.mahmud@example.com",
    name: "Rumana Ahmed",
    phone: "+8801811000026",
    email: "rumana.ahmed@example.com",
    age: 52,
    gender: "female",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(7),
    notes: "Dialysis plan review.",
  },
  {
    doctorEmail: "hasan.mahmud@example.com",
    name: "Khaled Rahman",
    phone: "+8801811000027",
    email: "khaled.rahman@example.com",
    age: 48,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(9),
    notes: "Creatinine check scheduled.",
  },
  {
    doctorEmail: "priyanka.das@example.com",
    name: "Suborna Das",
    phone: "+8801811000028",
    email: "suborna.das@example.com",
    age: 44,
    gender: "female",
    condition: "recovering",
    status: "follow-up",
    visitDate: daysFromToday(-11),
    notes: "Chemotherapy recovery review.",
  },
  {
    doctorEmail: "priyanka.das@example.com",
    name: "Faisal Ahmed",
    phone: "+8801811000029",
    email: "faisal.ahmed@example.com",
    age: 57,
    gender: "male",
    condition: "critical",
    status: "admitted",
    visitDate: daysFromToday(-3),
    notes: "Oncology ward monitoring.",
  },
  {
    doctorEmail: "priyanka.das@example.com",
    name: "Rehana Khatun",
    phone: "+8801811000030",
    email: "rehana.khatun@example.com",
    age: 61,
    gender: "female",
    condition: "stable",
    status: "scheduled",
    visitDate: daysFromToday(11),
    notes: "Screening appointment.",
  },
  {
    doctorEmail: "mehedi.alam@example.com",
    name: "Sabbir Alam",
    phone: "+8801811000031",
    email: "sabbir.alam@example.com",
    age: 26,
    gender: "male",
    condition: "stable",
    status: "discharged",
    visitDate: daysFromToday(-16),
    notes: "Sinus infection resolved.",
  },
  {
    doctorEmail: "mehedi.alam@example.com",
    name: "Lubna Hoque",
    phone: "+8801811000032",
    email: "lubna.hoque@example.com",
    age: 35,
    gender: "female",
    condition: "observation",
    status: "follow-up",
    visitDate: daysFromToday(-2),
    notes: "Hearing assessment follow-up.",
  },
  {
    doctorEmail: "mehedi.alam@example.com",
    name: "Rakibul Islam",
    phone: "+8801811000033",
    email: "rakibul.islam@example.com",
    age: 42,
    gender: "male",
    condition: "recovering",
    status: "scheduled",
    visitDate: daysFromToday(12),
    notes: "ENT procedure review.",
  },
  {
    doctorEmail: "farhana.yasmin@example.com",
    name: "Tanjila Noor",
    phone: "+8801811000034",
    email: "tanjila.noor@example.com",
    age: 30,
    gender: "female",
    condition: "stable",
    status: "follow-up",
    visitDate: daysFromToday(-6),
    notes: "Counseling follow-up.",
  },
  {
    doctorEmail: "farhana.yasmin@example.com",
    name: "Shahriar Kabir",
    phone: "+8801811000035",
    email: "shahriar.kabir@example.com",
    age: 38,
    gender: "male",
    condition: "observation",
    status: "scheduled",
    visitDate: daysFromToday(13),
    notes: "Anxiety management review.",
  },
  {
    doctorEmail: "farhana.yasmin@example.com",
    name: "Afsana Mimi",
    phone: "+8801811000036",
    email: "afsana.mimi@example.com",
    age: 22,
    gender: "female",
    condition: "recovering",
    status: "discharged",
    visitDate: daysFromToday(-18),
    notes: "Medication response improved.",
  },
];

const main = async () => {
  await connectToDatabase();

  const passwordHash = await hash(adminCredentials.password, env.BCRYPT_SALT_ROUNDS);

  await UserModel.updateOne(
    { email: adminCredentials.email },
    {
      $set: {
        name: adminCredentials.name,
        email: adminCredentials.email,
        password: passwordHash,
        role: adminCredentials.role,
      },
    },
    { upsert: true }
  );

  await DoctorModel.bulkWrite(
    doctors.map((doctor) => ({
      updateOne: {
        filter: { email: doctor.email },
        update: { $set: doctor },
        upsert: true,
      },
    }))
  );

  const seededDoctors = await DoctorModel.find({
    email: { $in: doctors.map((doctor) => doctor.email) },
  }).lean();
  const doctorIdByEmail = new Map(seededDoctors.map((doctor) => [doctor.email, doctor._id]));
  const patients = patientSeeds.map(({ doctorEmail, ...patient }) => {
    const doctorId = doctorIdByEmail.get(doctorEmail);

    if (!doctorId) {
      throw new Error(`Seed doctor not found for ${doctorEmail}`);
    }

    return { ...patient, doctorId };
  });

  await Promise.all(
    patients.map((patient) =>
      PatientModel.updateOne(
        { email: patient.email },
        {
          $set: patient,
        },
        { upsert: true }
      )
    )
  );

  await disconnectFromDatabase();

  console.info("Seed completed");
  console.info(`Admin email: ${adminCredentials.email}`);
  console.info(`Admin password: ${adminCredentials.password}`);
};

void main().catch(async (error) => {
  console.error(error);
  await disconnectFromDatabase();
  process.exit(1);
});
